# Generated by Django 3.2.5 on 2022-03-18 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_category_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 10, 23, 27, 699425, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='choice',
            name='vote_num',
            field=models.IntegerField(default=0),
        ),
    ]
